# Generated by Django 2.2.7 on 2019-11-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_registro', models.DateTimeField(editable=False, verbose_name='Data de registro do chamado')),
                ('situacao', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em atendimento'), (3, 'Fechado')], default=1, verbose_name='Situação do Chamado')),
                ('tipo', models.IntegerField(choices=[(1, 'Reparo'), (2, 'Compra'), (3, 'Troca')], verbose_name='Tipo de Chamado')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigc.Setor')),
            ],
        ),
    ]
