# Generated by Django 2.2.7 on 2019-11-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigc', '0002_chamado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_de_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do chamado'),
        ),
    ]
